/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UAS_GUI_ADY;

import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.table.TableModel;

public class JadwalKereta extends javax.swing.JFrame {

    /**
     * Creates new form JadwalKereta
     */
    public JadwalKereta() {
        initComponents();
        this.setTitle("Jadwal Kereta");
        this.setLocationRelativeTo(this);
        
        Koneksi konek = new Koneksi();
        konek.Koneksi();
        this.statuskoneksi.setText(konek.statuskoneksi);
        table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inTanggal = new com.toedter.calendar.JDateChooser();
        inJam = new javax.swing.JTextField();
        inAsal = new javax.swing.JTextField();
        inTujuan = new javax.swing.JTextField();
        inSimpan = new javax.swing.JButton();
        inEdit = new javax.swing.JButton();
        inReset = new javax.swing.JButton();
        inHapus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        statuskoneksi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inKelas = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        opsi = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeljadwal = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setText("Buat Jadwal Kereta");

        inJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inJamActionPerformed(evt);
            }
        });

        inAsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inAsalActionPerformed(evt);
            }
        });

        inTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inTujuanActionPerformed(evt);
            }
        });

        inSimpan.setText("Simpan");
        inSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inSimpanActionPerformed(evt);
            }
        });

        inEdit.setText("Edit");
        inEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inEditActionPerformed(evt);
            }
        });

        inReset.setText("Reset");
        inReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inResetActionPerformed(evt);
            }
        });

        inHapus.setText("Hapus");
        inHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inHapusActionPerformed(evt);
            }
        });

        jLabel3.setText("Tanggal");

        jLabel4.setText("Jam");

        jLabel5.setText("Kelas");

        jLabel6.setText("Asal");

        jLabel7.setText("Tujuan");

        statuskoneksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statuskoneksiActionPerformed(evt);
            }
        });

        jLabel2.setText("Status Koneksi");

        inKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ekonomi", "Eksekutif", "Bisnis" }));
        inKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inKelasActionPerformed(evt);
            }
        });

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        opsi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Pencarian--", "Tanggal", "Jam", "Kelas", "Asal", "Tujuan" }));
        opsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opsiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(inJam)
                        .addComponent(inAsal)
                        .addComponent(inTujuan)
                        .addComponent(inKelas, 0, 88, Short.MAX_VALUE)))
                .addGap(71, 71, 71))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(statuskoneksi, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inSimpan)
                        .addGap(48, 48, 48)
                        .addComponent(inEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inReset)
                        .addGap(40, 40, 40)
                        .addComponent(inHapus)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inSimpan)
                    .addComponent(inEdit)
                    .addComponent(inReset)
                    .addComponent(inHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statuskoneksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(opsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        jTabbedPane1.addTab("Buat Jadwal", jPanel1);

        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setText("Daftar Jadwal Kereta");

        tabeljadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "Jam", "Kelas", "Asal", "Tujuan"
            }
        ));
        tabeljadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeljadwalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeljadwal);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(168, 168, 168))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Daftar Jadwal", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Statement pst;
    ResultSet rs;
    
    public void table() {
        Koneksi konek = new Koneksi();
        konek.Koneksi();
        
        try {
            
            String sql = "SELECT * FROM tbkereta";
            pst = konek.con.createStatement();
            rs = pst.executeQuery(sql);
            tabeljadwal.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    public void selectByTanggal(Date tgl) {
        Koneksi konek = new Koneksi();
        konek.Koneksi();
        
        try {
            
            String sql = "select * from tbkereta where tgl like '%" + tgl + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            tabeljadwal.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void selectByJam(String jam) {
        Koneksi konek = new Koneksi();
        konek.Koneksi();
        
        try {
            
            String sql = "select * from tbkereta where jam like '%" + jam + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            tabeljadwal.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void selectByKelas(String kelas) {
        Koneksi konek = new Koneksi();
        konek.Koneksi();
        
        try {
            
            String sql = "SELECT * FROM tbkereta WHERE kelas like '%" + kelas + "%'";

    pst = konek.con.prepareStatement(sql);

    pst.setCursorName(sql);

    rs = pst.executeQuery(sql);

    tabeljadwal.setModel(DbUtils.resultSetToTableModel(rs));

  } catch (Exception e) {

    JOptionPane.showMessageDialog(null, e);

  }
    }
    
    public void selectByAsal(String asal) {
        Koneksi konek = new Koneksi();
        konek.Koneksi();
        
        try {
            
            String sql = "select * from tbkereta where asal like '%" + asal + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            tabeljadwal.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void selectByTujuan(String tujuan) {
        Koneksi konek = new Koneksi();
        konek.Koneksi();
        
        try {
            
            String sql = "select * from tbkereta where tujuan like '%" + tujuan + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            tabeljadwal.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void inJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inJamActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_inJamActionPerformed

    private void inAsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inAsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inAsalActionPerformed

    private void inTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inTujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inTujuanActionPerformed

    private void inKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inKelasActionPerformed
        // TODO add your handling code here:
        
        String kelas = "";        
        if (inKelas.getSelectedIndex() == 0) {
            kelas = "Ekonomi";
        } else if (inKelas.getSelectedIndex() == 1) {
            kelas = "Bisnis";
        } else if (inKelas.getSelectedIndex() == 2) {
            kelas = "Eksekutif";
        } else {
            return;            
        }
    }//GEN-LAST:event_inKelasActionPerformed

    private void inSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inSimpanActionPerformed
        
        Insert in = new Insert();
        Date selectedDate = inTanggal.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tgl = dateFormat.format(inTanggal.getDate());
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate date = inTanggal.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        String dateString = date.format(formatter);
        String jam = inJam.getText();
        String asal = inAsal.getText();
        String tujuan = inTujuan.getText();
        
        String kelas = "";        
        if (inKelas.getSelectedIndex() == 0) {
            kelas = "Ekonomi";
        } else if (inKelas.getSelectedIndex() == 1) {
            kelas = "Eksekutif";
        } else if (inKelas.getSelectedIndex() == 2) {
            kelas = "Bisnis";
        } else {
            return;            
        }
        
        in.Insert(tgl, jam, kelas, asal, tujuan);
        
        table();
        
    }//GEN-LAST:event_inSimpanActionPerformed

    private void inEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inEditActionPerformed
        Koneksi konek = new Koneksi();
        konek.Koneksi();
        
        Date selectedDate = inTanggal.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tgl = dateFormat.format(inTanggal.getDate());
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate date = inTanggal.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        String dateString = date.format(formatter);
        String jam = inJam.getText();
        
        String kelas = "";        
        if (inKelas.getSelectedIndex() == 0) {
            kelas = "Ekonomi";
        } else if (inKelas.getSelectedIndex() == 1) {
            kelas = "Eksekutif";
        } else if (inKelas.getSelectedIndex() == 2) {
            kelas = "Bisnis";
        } else {
            return;            
        }
        
        String asal = inAsal.getText();
        String tujuan = inTujuan.getText();
        
        Edit ubah = new Edit();
        ubah.Edit(tgl, jam, kelas, asal, tujuan);
        
        table();        // TODO add your handling code here:
    }//GEN-LAST:event_inEditActionPerformed

    private void inResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inResetActionPerformed
        
        inTanggal.setDate(null);
        inJam.setText("");
        String kelas = "";        
        if (inKelas.getSelectedIndex() == 0) {
            kelas = "Ekonomi";
        } else if (inKelas.getSelectedIndex() == 1) {
            kelas = "Eksekutif";
        } else if (inKelas.getSelectedIndex() == 2) {
            kelas = "Bisnis";
        } else {
            return;            
        }
        
        inAsal.setText("");
        inTujuan.setText("");
        
    }//GEN-LAST:event_inResetActionPerformed

    private void inHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inHapusActionPerformed

Koneksi konek = new Koneksi();
konek.Koneksi();
Hapus hps = new Hapus();
hps.Hapus(inJam.getText());
       
table();
    }//GEN-LAST:event_inHapusActionPerformed

    private void tabeljadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeljadwalMouseClicked
        // TODO add your handling code here:
        
int selectedRow = tabeljadwal.getSelectedRow();
        
        TableModel model = tabeljadwal.getModel();
       
        inTanggal.setDate((Date) model.getValueAt(selectedRow, 0));
        inJam.setText(model.getValueAt(selectedRow, 1).toString());
        inJam.setToolTipText(model.getValueAt(selectedRow, 2).toString());
        inAsal.setText(model.getValueAt(selectedRow,3 ).toString());
        inTujuan.setText(model.getValueAt(selectedRow, 4).toString());
        

               
        
    }//GEN-LAST:event_tabeljadwalMouseClicked

    private void statuskoneksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statuskoneksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statuskoneksiActionPerformed

    private void opsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opsiActionPerformed
 if (opsi.getSelectedIndex() == 1) {
            selectByTanggal(inTanggal.getDate());
        } else if (opsi.getSelectedIndex() == 2) {
            selectByJam(inJam.getText());
        } else if (opsi.getSelectedIndex() == 3) {
            selectByKelas(inKelas.getItemAt(WIDTH));
        } else if (opsi.getSelectedIndex() == 4) {
            selectByAsal(inAsal.getText());
        } else if (opsi.getSelectedIndex() == 5) {
            selectByTujuan(inTujuan.getText());
        } else {
            table();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_opsiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JadwalKereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JadwalKereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JadwalKereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JadwalKereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JadwalKereta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inAsal;
    private javax.swing.JButton inEdit;
    private javax.swing.JButton inHapus;
    private javax.swing.JTextField inJam;
    private javax.swing.JComboBox<String> inKelas;
    private javax.swing.JButton inReset;
    private javax.swing.JButton inSimpan;
    private com.toedter.calendar.JDateChooser inTanggal;
    private javax.swing.JTextField inTujuan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> opsi;
    private javax.swing.JTextField statuskoneksi;
    private javax.swing.JTable tabeljadwal;
    // End of variables declaration//GEN-END:variables
}
